name: Trigger from Azure Function

on:
  workflow_dispatch:
    inputs:
      example_parameter:
        description: 'An example input'
        required: false
        default: 'value'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Print message
        run: echo "Workflow triggered from Azure Function App"
